name: Build and Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install python dependencies
        run: |
          pip install -r ${{github.workspace}}/requirements.txt

      - name: Run conan install
        run: conan profile detect && conan install . -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True -sbuild_type=Release -of=conan --build=missing

      - name: Configure CMake
        run: cmake -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/conan/build/Release/generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON -B ${{github.workspace}}/build/Release -S .

      - name: Build
        run: cmake --build ${{github.workspace}}/build/Release -j4

      - name: Package the library
        id: package
        run: |
          cmake --install ${{github.workspace}}/build/Release --prefix package/Release
          echo "Packing blur-detection-lib-package-Release completed"

      - name: Debug package directory
        run: |
          echo "Listing contents of package directory:"
          ls -R package/Release
        shell: bash

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: blur-detection-lib-package-Release
          path: package/Release/bin/test/

  # Test Job
  test:
    runs-on: ubuntu-latest
    needs: build # Waits for the build job to complete
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: blur-detection-lib-package-Release
          path: package/Release/bin/test/

      - name: Run Tests
        run: |
          ./bin/test/test_blur_detection
        working-directory: package/Release
